### ISSUE TITLE
I'm getting permission denied error in windows 10 Anaconda

### ISSUE THREAD

**Issue by WrathofBhuvan11** [conda-forge/nipype-feedstock#41]
Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by mgxd** [comment]
@WrathofBhuvan11 can you post the console output?

**Comment by effigies** [comment]
@WrathofBhuvan11 Please reopen if this is still an issue.
