### ISSUE TITLE
Depend on matplotlib-base instead of matplotlib (improvement)

### ISSUE THREAD

**Issue by abrys** [conda-forge/nipype-feedstock#60]
If possible it would be a lot cleaner to depend on matplotlib-base instead of matplotlib as this now results in a cascading of mostly unnecessary dependencies.

**Comment by effigies** [comment]
Could you submit a PR? And is this a change that should go in the main package as well, or is it a quirk of conda packaging?

**Comment by abrys** [comment]
As far as i understand it is a conda only thing as this will only add the required dependencies and not the optional similar to what pip will do by default.
Will see if I can create a PR in one of the next days.
